version: '3'
services:
  qiime2-metabolomics-streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qiime2-metabolomics-streamlit
    volumes:
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: fbmn-qiime2.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: fbmn-qiime2.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net